# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConnector',
            fields=[
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='Whether product available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountConnectorGroup',
            fields=[
                ('count', models.IntegerField(default=0)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discount price')),
                ('available', models.BooleanField(default=True, verbose_name='Whether group is available available')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.AccountConnector', verbose_name='Related account connector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discount price')),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.AccountConnectorGroup', verbose_name='account group')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='Whether product available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Product country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('count', models.IntegerField(default=0)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Discount price')),
                ('available', models.BooleanField(default=True, verbose_name='Whether group is available available')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Product', verbose_name='Related product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('scanned_number_of_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='productgroup',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Scanner', verbose_name='Related scanner'),
        ),
        migrations.AddField(
            model_name='paymentlist',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.ProductGroup', verbose_name='product group'),
        ),
    ]
