# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='scanner',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='scanner',
            field=models.ManyToManyField(to='payment.Scanner', verbose_name='Related scanner'),
        ),
    ]
