# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20171109_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='scanner',
            new_name='scanners',
        ),
        migrations.AlterField(
            model_name='paymentlist',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total price'),
        ),
    ]
