# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20171109_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='scanners',
        ),
        migrations.AddField(
            model_name='paymentlist',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Scanner', verbose_name='scanner'),
        ),
    ]
